spring.application.name=Latia_Lati
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/latia
spring.datasource.username=postgres
spring.datasource.password=postgre
server.port=8080
jwt.secret=${JWT_SECRET}
