-- Esquema PostgreSQL y datos ficticios de LATIA.
-- Ejecutar conectado a la base vacia latia.
-- Clave de las cuentas de ejemplo: LatiaDemo2026!

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id_user bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(150) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at date NOT NULL DEFAULT CURRENT_DATE,
    updated_at date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol varchar(30) NOT NULL,
    id_user bigint NOT NULL REFERENCES users (id_user),
    CONSTRAINT uq_roles_user_role UNIQUE (id_user, rol)
);

CREATE TABLE health_profiles (
    id_health_profile bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_owner_user bigint NOT NULL REFERENCES users (id_user),
    id_holder_user bigint UNIQUE REFERENCES users (id_user),
    birth_date date,
    sex varchar(30),
    blood_type varchar(5),
    phone varchar(30),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz
);

CREATE TABLE emergency_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_health_profile bigint NOT NULL REFERENCES health_profiles (id_health_profile),
    name varchar(150) NOT NULL,
    phone varchar(30) NOT NULL,
    relationship varchar(80),
    primary_contact boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz
);

CREATE TABLE family_relationships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_origin_profile bigint NOT NULL REFERENCES health_profiles (id_health_profile),
    id_relative_profile bigint NOT NULL REFERENCES health_profiles (id_health_profile),
    relationship_type varchar(80) NOT NULL
);

CREATE TABLE medical_conditions (
    id_medical_condition bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_medical_condition varchar(150) NOT NULL,
    description_medical_condition varchar(255) NOT NULL
);

CREATE TABLE clinical_records (
    id_clinical_record bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_health_profile bigint NOT NULL REFERENCES health_profiles (id_health_profile),
    record_type varchar(20) NOT NULL,
    title varchar(150) NOT NULL,
    description text,
    event_date timestamp NOT NULL,
    professional_name varchar(150) NOT NULL,
    id_condition bigint NOT NULL REFERENCES medical_conditions (id_medical_condition)
);

CREATE TABLE exam_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinical_record bigint NOT NULL REFERENCES clinical_records (id_clinical_record),
    parameter_name varchar(150) NOT NULL,
    result_value varchar(150) NOT NULL,
    unit varchar(50)
);

CREATE TABLE medications (
    id_medications bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_medications varchar(50) NOT NULL,
    dosage_form varchar(25) NOT NULL,
    strength varchar(50)
);

CREATE TABLE medication_treatments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinical_record bigint NOT NULL REFERENCES clinical_records (id_clinical_record),
    id_medication bigint NOT NULL REFERENCES medications (id_medications),
    dose varchar(100) NOT NULL,
    administration_route varchar(80) NOT NULL,
    start_date date NOT NULL,
    end_date date
);

CREATE TABLE medication_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medicament_treatment bigint NOT NULL REFERENCES medication_treatments (id),
    reminder_time timestamp NOT NULL,
    interval_hours integer NOT NULL
);

CREATE TABLE medical_documents (
    id_medical_documents bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type varchar(50) NOT NULL,
    title varchar(100) NOT NULL,
    file_url varchar(200) NOT NULL,
    document_date date,
    id_health_profile bigint NOT NULL REFERENCES health_profiles (id_health_profile)
);

CREATE TABLE clinical_record_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinical_record bigint NOT NULL REFERENCES clinical_records (id_clinical_record),
    id_medical_document bigint NOT NULL REFERENCES medical_documents (id_medical_documents)
);

INSERT INTO users (
    id_user, first_name, last_name, username, email, password_hash, active, created_at, updated_at
) VALUES
    (1, 'Valeria', 'Quiroz', 'latia.ficticio.01', 'valeria.quiroz@example.com',
     crypt('LatiaDemo2026!', gen_salt('bf', 10)), true, CURRENT_DATE, CURRENT_DATE),
    (2, 'Mateo', 'Quiroz', 'latia.ficticio.02', 'mateo.quiroz@example.com',
     crypt('LatiaDemo2026!', gen_salt('bf', 10)), true, CURRENT_DATE, CURRENT_DATE),
    (3, 'Camila', 'Rojas', 'latia.ficticio.03', 'camila.rojas@example.com',
     crypt('LatiaDemo2026!', gen_salt('bf', 10)), true, CURRENT_DATE, CURRENT_DATE),
    (4, 'Diego', 'Rojas', 'latia.ficticio.04', 'diego.rojas@example.com',
     crypt('LatiaDemo2026!', gen_salt('bf', 10)), true, CURRENT_DATE, CURRENT_DATE),
    (5, 'Rosa', 'Quiroz', 'latia.ficticio.05', 'rosa.quiroz@example.com',
     crypt('LatiaDemo2026!', gen_salt('bf', 10)), true, CURRENT_DATE, CURRENT_DATE);

INSERT INTO roles (id, rol, id_user) VALUES
    (1, 'ROLE_USER', 1), (2, 'ROLE_USER', 2), (3, 'ROLE_USER', 3),
    (4, 'ROLE_USER', 4), (5, 'ROLE_USER', 5);

INSERT INTO health_profiles (
    id_health_profile, id_owner_user, birth_date, sex, blood_type, phone, active
) VALUES
    (1, 1, DATE '1991-04-18', 'Femenino', 'O+', '+51 900 000 001', true),
    (2, 2, DATE '1986-11-02', 'Masculino', 'A-', '+51 900 000 002', true),
    (3, 3, DATE '1998-07-25', 'Femenino', 'B+', '+51 900 000 003', true),
    (4, 4, DATE '1979-02-14', 'Masculino', 'O-', '+51 900 000 004', true),
    (5, 5, DATE '1964-09-09', 'Femenino', 'AB+', '+51 900 000 005', true);

INSERT INTO medical_conditions (id_medical_condition, name_medical_condition, description_medical_condition) VALUES
    (1, 'Asma persistente leve', 'Sintomas ocasionales con ejercicio; sin crisis recientes y con respuesta al inhalador.'),
    (2, 'Migraña episodica', 'Cefalea pulsante ocasional acompañada de fotofobia, sin signos neurologicos de alarma.'),
    (3, 'Rinitis alergica estacional', 'Congestion y estornudos durante la temporada de polen, sin dificultad respiratoria.'),
    (4, 'Anemia ferropenica leve', 'Hemoglobina por debajo del rango esperado; en seguimiento con suplementacion de hierro.'),
    (5, 'Hipertension arterial esencial', 'Presion arterial controlada con tratamiento y monitoreo domiciliario.');

INSERT INTO medications (id_medications, name_medications, dosage_form, strength) VALUES
    (1, 'Salbutamol', 'Inhalador', '100 mcg por dosis'),
    (2, 'Paracetamol', 'Tableta', '500 mg'),
    (3, 'Loratadina', 'Tableta', '10 mg'),
    (4, 'Sulfato ferroso', 'Tableta', '300 mg'),
    (5, 'Losartan', 'Tableta', '50 mg');

INSERT INTO clinical_records (
    id_clinical_record, id_health_profile, record_type, title, description,
    event_date, professional_name, id_condition
) VALUES
    (1, 1, 'Consulta', 'Control respiratorio',
     'Tos y sibilancias ocasionales al realizar ejercicio. Se revisa la tecnica de inhalacion y se indica control.',
     CURRENT_DATE - INTERVAL '10 days', 'Dra. Andrea Salazar', 1),
    (2, 2, 'Consulta', 'Evaluacion por cefalea',
     'Cefalea pulsante unilateral con fotofobia, sin signos de alarma. Se recomienda hidratacion y seguimiento.',
     CURRENT_DATE - INTERVAL '11 days', 'Dr. Pablo Herrera', 2),
    (3, 3, 'Seguimiento', 'Control de rinitis alergica',
     'Estornudos y congestion recurrentes durante temporada de polen. Se revisan medidas de control ambiental.',
     CURRENT_DATE - INTERVAL '12 days', 'Dra. Natalia Campos', 3),
    (4, 4, 'Laboratorio', 'Control de hemograma',
     'Cansancio durante las ultimas semanas. Hemograma compatible con anemia leve; se indica control posterior.',
     CURRENT_DATE - INTERVAL '13 days', 'Dr. Luis Fernandez', 4),
    (5, 5, 'Control', 'Control de presion arterial',
     'Sin sintomas actuales. Se revisan mediciones domiciliarias y recomendaciones de actividad fisica.',
     CURRENT_DATE - INTERVAL '14 days', 'Dra. Elena Vargas', 5);

INSERT INTO emergency_contacts (id, id_health_profile, name, phone, relationship, primary_contact) VALUES
    (1, 1, 'Mateo Quiroz', '+51 900 000 101', 'Hermano', true),
    (2, 2, 'Valeria Quiroz', '+51 900 000 102', 'Hermana', true),
    (3, 3, 'Diego Rojas', '+51 900 000 103', 'Esposo', true),
    (4, 4, 'Camila Rojas', '+51 900 000 104', 'Esposa', true),
    (5, 5, 'Lucia Quiroz', '+51 900 000 105', 'Hija', true);

INSERT INTO family_relationships (id, id_origin_profile, id_relative_profile, relationship_type) VALUES
    (1, 1, 2, 'Hermanos'), (2, 2, 1, 'Hermanos'),
    (3, 3, 4, 'Esposos'), (4, 4, 3, 'Esposos'),
    (5, 5, 1, 'Madre e hija');

INSERT INTO exam_results (id, id_clinical_record, parameter_name, result_value, unit) VALUES
    (1, 1, 'Saturacion de oxigeno', '97', '%'),
    (2, 2, 'Presion arterial', '118/76', 'mmHg'),
    (3, 3, 'IgE total', '186', 'UI/mL'),
    (4, 4, 'Hemoglobina', '10.8', 'g/dL'),
    (5, 5, 'Presion arterial', '132/82', 'mmHg');

INSERT INTO medication_treatments (
    id, id_clinical_record, id_medication, dose, administration_route, start_date, end_date
) VALUES
    (1, 1, 1, '2 inhalaciones cuando sea necesario', 'Inhalatoria', CURRENT_DATE - 10, CURRENT_DATE + 20),
    (2, 2, 2, '1 tableta si inicia la cefalea', 'Oral', CURRENT_DATE - 9, CURRENT_DATE + 21),
    (3, 3, 3, '1 tableta al dia', 'Oral', CURRENT_DATE - 8, CURRENT_DATE + 22),
    (4, 4, 4, '1 tableta al dia con alimentos', 'Oral', CURRENT_DATE - 7, CURRENT_DATE + 23),
    (5, 5, 5, '1 tableta al dia', 'Oral', CURRENT_DATE - 6, NULL);

INSERT INTO medication_schedules (id, id_medicament_treatment, reminder_time, interval_hours) VALUES
    (1, 1, CURRENT_DATE + TIME '08:00', 6),
    (2, 2, CURRENT_DATE + TIME '09:00', 8),
    (3, 3, CURRENT_DATE + TIME '07:00', 24),
    (4, 4, CURRENT_DATE + TIME '08:00', 24),
    (5, 5, CURRENT_DATE + TIME '20:00', 24);

INSERT INTO medical_documents (
    id_medical_documents, document_type, title, file_url, document_date, id_health_profile
) VALUES
    (1, 'Resultado de laboratorio', 'Espirometria de control',
     'https://example.com/latia/documentos-ficticios/expediente-1.pdf', CURRENT_DATE - 10, 1),
    (2, 'Receta', 'Indicaciones para cefalea',
     'https://example.com/latia/documentos-ficticios/expediente-2.pdf', CURRENT_DATE - 11, 2),
    (3, 'Informe medico', 'Evaluacion de rinitis alergica',
     'https://example.com/latia/documentos-ficticios/expediente-3.pdf', CURRENT_DATE - 12, 3),
    (4, 'Resultado de laboratorio', 'Hemograma completo',
     'https://example.com/latia/documentos-ficticios/expediente-4.pdf', CURRENT_DATE - 13, 4),
    (5, 'Control clinico', 'Registro de presion arterial',
     'https://example.com/latia/documentos-ficticios/expediente-5.pdf', CURRENT_DATE - 14, 5);

INSERT INTO clinical_record_documents (id, id_clinical_record, id_medical_document) VALUES
    (1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 4), (5, 5, 5);

SELECT setval(pg_get_serial_sequence('users', 'id_user'), (SELECT MAX(id_user) FROM users));
SELECT setval(pg_get_serial_sequence('roles', 'id'), (SELECT MAX(id) FROM roles));
SELECT setval(pg_get_serial_sequence('health_profiles', 'id_health_profile'), (SELECT MAX(id_health_profile) FROM health_profiles));
SELECT setval(pg_get_serial_sequence('emergency_contacts', 'id'), (SELECT MAX(id) FROM emergency_contacts));
SELECT setval(pg_get_serial_sequence('family_relationships', 'id'), (SELECT MAX(id) FROM family_relationships));
SELECT setval(pg_get_serial_sequence('medical_conditions', 'id_medical_condition'), (SELECT MAX(id_medical_condition) FROM medical_conditions));
SELECT setval(pg_get_serial_sequence('clinical_records', 'id_clinical_record'), (SELECT MAX(id_clinical_record) FROM clinical_records));
SELECT setval(pg_get_serial_sequence('exam_results', 'id'), (SELECT MAX(id) FROM exam_results));
SELECT setval(pg_get_serial_sequence('medications', 'id_medications'), (SELECT MAX(id_medications) FROM medications));
SELECT setval(pg_get_serial_sequence('medication_treatments', 'id'), (SELECT MAX(id) FROM medication_treatments));
SELECT setval(pg_get_serial_sequence('medication_schedules', 'id'), (SELECT MAX(id) FROM medication_schedules));
SELECT setval(pg_get_serial_sequence('medical_documents', 'id_medical_documents'), (SELECT MAX(id_medical_documents) FROM medical_documents));
SELECT setval(pg_get_serial_sequence('clinical_record_documents', 'id'), (SELECT MAX(id) FROM clinical_record_documents));
